### ISSUE TITLE
Chapter 5 top-level header in ToC hyperlinks to wrong destination

### ISSUE THREAD

**Issue by mattwarkentin** [wlandau/targets-manual#18]
## Prework

* [x] I understand and agree to this repository's [code of conduct](https://github.com/wlandau/targets-manual/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to this repository's [contributing guidelines](https://github.com/wlandau/targets-manual/blob/master/CONTRIBUTING.md).
* [x] I am reasonably sure this is a genuine bug in this repository's code and most likely not a user error. (If you run into an error and do not know the cause, please submit a "Trouble" issue instead.)

## Description

Chapter 5 header in table of contents hyperlinks to Section 2.2.

**Comment by wlandau** [comment]
Yup, I think we need strictly unique header names. Thanks.
