### ISSUE TITLE
Cloud computing guide

### ISSUE THREAD

**Issue by wlandau** [wlandau/targets-manual#21]
## Prework

* [x] I understand and agree to this repository's [code of conduct](https://github.com/wlandau/targets-manual/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to this repository's [contributing guidelines](https://github.com/wlandau/targets-manual/blob/master/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

There is a community misconception that `targets` (and `drake`) do not have HPC capabilities beyond parallel computing over the cores of a single local machine. On the contrary, both tools support distributed computing on clusters (guides [here](https://wlandau.github.io/targets-manual/hpc.html#clustermq-remotely) and [here](https://books.ropensci.org/drake/hpc.html#the-clustermq-backend)) and the workers do not necessarily need access to the file system of the master process. (In fact, I designed `targets` with an [efficient dynamic branching model](https://wlandau.github.io/targets/articles/need.html#improved-parallel-efficiency-1) to go beyond the inherent limitations of map-reduce-like scheduling algorithms and conserve computing resources.) However, I do realize that data scientists from smaller institutions do not always have access to clusters, and an increasing number of folks use AWS. [AWS ParallelCluster](https://aws.amazon.com/hpc/parallelcluster/) could be a way to deploy pipelines to the cloud without any need to modify `targets` itself. If it works, we should probably write a tutorial either in the [existing HPC chapter](https://wlandau.github.io/targets-manual/hpc.html) or a chapter of its own.

https://github.com/wlandau/tarchetypes/issues/8 could be an alternative way to deploy to AWS. The advantage of https://github.com/wlandau/tarchetypes/issues/8 is that we should also get the data versioning capabilities of Metaflow for free, and Metaflow may take care of a lot of the AWS setup. However, each new `tar_metaflow()` will require its own local R worker in order to avoid blocking the master process, which is not ideal.

**Comment by wlandau** [comment]
The biggest potential difference I see to this (relative to Metaflow's approach to AWS) is that the `targets` data store will probably live locally. But it's not so bad because `drake` users want this behavior anyway so they can explore data interactively (example: https://github.com/ropensci/drake/issues/1295). And as @noamross pointed out, `aws.s3::s3sync()` can upload the data store to an S3 bucket. `_targets/` is super light relative to `.drake/`, so this shouldn't be too painful for most projects.

**Comment by wlandau** [comment]
If `cloudyr` packages still work, `tar_make_future()` can probably already talk to multiple AWS instances: https://gist.github.com/DavisVaughan/5aac4a2757c0947a499d25d28a8ca89b

**Comment by wlandau** [comment]
@MilesMcBain, your team uses AWS, right? What's your preferred way to interact with it?

**Comment by wlandau** [comment]
I read up more on AWS ParallelCluster, AWS Batch, and Metaflow's HPC, and `targets`' capabilities are not ready for a cloud computing guide yet. But I think development on top of `paws` can get us much of the way there.

**Comment by MilesMcBain** [comment]
Hey @wlandau, so far we have preferred to call the AWS CLI directly. This is mainly due to a combination of very simple workflows, and uncertainty about the stability of the AWS-R ecosystem.

**Comment by wlandau** [comment]
That's helpful, I know `cloudyr` had a rough time. What do you think about `paws`? I'm hoping it can help with https://github.com/wlandau/targets/issues/152 either directly or through https://github.com/HenrikBengtsson/future/issues/415 or https://github.com/mschubert/clustermq/issues/102#issuecomment-687693826.

**Comment by wlandau** [comment]
Reopening. I plan to write about https://github.com/wlandau/targets/pull/176 at least.

I will keep my eye on R + cloud packages. Looks like `aws.s3` has been updated in May, which is a good sign. And `paws` is under constant development but isn't quite there for the new S3 feature set in `targets`.

**Comment by wlandau-lilly** [comment]
Just wrote about S3 integration in the new cloud chapter. Will reopen after https://github.com/wlandau/targets/issues/152.
